name: Wake Up Streamlit Apps

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 */7 * *"

jobs:
  wake_up_apps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Selenium
        run: pip install selenium


      - name: Wake up Streamlit apps
        run: python wake_up_apps.py

      - name: Upload log artifact
        uses: actions/upload-artifact@v2
        with:
          name: wakeup-log
          path: wakeup_log.txt
