name: Wake Up Streamlit Apps

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 */7 * *"

jobs:
  wake-up:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install selenium

      - name: Download and set up ChromeDriver
        run: |
          CHROME_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
          CHROMEDRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION/chromedriver_linux64.zip" | grep -oP '(\d+\.\d+\.\d+\.\d+)' | head -1)
          curl -L -o chromedriver.zip "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/

      - name: Run Python script to wake up Streamlit apps
        run: python wake_up_streamlit.py
